//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolGerasimova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterials = new HashSet<ProductMaterials>();
        }
    
        public int material_id { get; set; }
        public int id_material_type { get; set; }
        public string material_name { get; set; }
        public string supplier { get; set; }
        public int package_quantity { get; set; }
        public string unit_measure { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }
        public decimal price { get; set; }
        public int stock_quantity { get; set; }
        public int min_quantity { get; set; }
    
        public virtual materialType materialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
    }
}
