//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolGerasimova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPol_Entities : DbContext
    {
        private static MasterPol_Entities _context;

        public static MasterPol_Entities GetContext()
        {
            if (_context == null)
                _context = new MasterPol_Entities();
            return _context;
        }
        public MasterPol_Entities()
            : base("name=MasterPol_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<materialType> materialType { get; set; }
        public virtual DbSet<Partner_Products> Partner_Products { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Pertner_type> Pertner_type { get; set; }
        public virtual DbSet<ProductMaterials> ProductMaterials { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
    }
}
