//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolGerasimova
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Partner_Products = new HashSet<Partner_Products>();
        }
    
        public int partner_id { get; set; }
        public int partner_type_id { get; set; }
        public string company_name { get; set; }
        public string director_lastName { get; set; }
        public string director_firstName { get; set; }
        public string director_patronymic { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
        public int rating { get; set; }

        // Добавленные вычисляемые свойства
        public int TotalSalesQuantity
        {
            get
            {
                if (Partner_Products == null || !Partner_Products.Any())
                    return 0;

                return Partner_Products.Sum(pp => pp.quantity_products);
            }
        }

        public decimal DiscountPercent
        {
            get
            {
                int totalQuantity = TotalSalesQuantity;

                if (totalQuantity >= 300000) return 15m;
                if (totalQuantity >= 50000) return 10m;
                if (totalQuantity >= 10000) return 5m;
                return 0m;
            }
        }

        public string DiscountDisplay
        {
            get
            {
                return $"{DiscountPercent}%";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_Products> Partner_Products { get; set; }
        public virtual Pertner_type Pertner_type { get; set; }
    }
}
