//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolGerasimova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_Products
    {
        public int id_partnerProducts { get; set; }
        public int id_products { get; set; }
        public int id_partner { get; set; }
        public int quantity_products { get; set; }
        public System.DateTime sales_data { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
