//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolGerasimova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterials
    {
        public int product_material_id { get; set; }
        public int product_id { get; set; }
        public int material_id { get; set; }
        public int quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
